package com.qf.with_my_car.pojo;

import lombok.Data;

import java.io.Serializable;
@Data
public class CarBrand implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.other_name
     *
     * @mbggenerated
     */
    private String otherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.english_name
     *
     * @mbggenerated
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.country_id
     *
     * @mbggenerated
     */
    private Integer countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.logo_url
     *
     * @mbggenerated
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.logo_meaning
     *
     * @mbggenerated
     */
    private String logoMeaning;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.first_char
     *
     * @mbggenerated
     */
    private String firstChar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.spell
     *
     * @mbggenerated
     */
    private String spell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.all_spell
     *
     * @mbggenerated
     */
    private String allSpell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.name_spell
     *
     * @mbggenerated
     */
    private String nameSpell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.name_all_spell
     *
     * @mbggenerated
     */
    private String nameAllSpell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.sale_status
     *
     * @mbggenerated
     */
    private Byte saleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.is_enabled
     *
     * @mbggenerated
     */
    private Byte isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.is_removed
     *
     * @mbggenerated
     */
    private Byte isRemoved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.do_time
     *
     * @mbggenerated
     */
    private Integer doTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.sync_time
     *
     * @mbggenerated
     */
    private Integer syncTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.id
     *
     * @return the value of car_brand.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.id
     *
     * @param id the value for car_brand.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.name
     *
     * @return the value of car_brand.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.name
     *
     * @param name the value for car_brand.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.other_name
     *
     * @return the value of car_brand.other_name
     *
     * @mbggenerated
     */
    public String getOtherName() {
        return otherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.other_name
     *
     * @param otherName the value for car_brand.other_name
     *
     * @mbggenerated
     */
    public void setOtherName(String otherName) {
        this.otherName = otherName == null ? null : otherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.english_name
     *
     * @return the value of car_brand.english_name
     *
     * @mbggenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.english_name
     *
     * @param englishName the value for car_brand.english_name
     *
     * @mbggenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.country_id
     *
     * @return the value of car_brand.country_id
     *
     * @mbggenerated
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.country_id
     *
     * @param countryId the value for car_brand.country_id
     *
     * @mbggenerated
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.logo_url
     *
     * @return the value of car_brand.logo_url
     *
     * @mbggenerated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.logo_url
     *
     * @param logoUrl the value for car_brand.logo_url
     *
     * @mbggenerated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.logo_meaning
     *
     * @return the value of car_brand.logo_meaning
     *
     * @mbggenerated
     */
    public String getLogoMeaning() {
        return logoMeaning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.logo_meaning
     *
     * @param logoMeaning the value for car_brand.logo_meaning
     *
     * @mbggenerated
     */
    public void setLogoMeaning(String logoMeaning) {
        this.logoMeaning = logoMeaning == null ? null : logoMeaning.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.first_char
     *
     * @return the value of car_brand.first_char
     *
     * @mbggenerated
     */
    public String getFirstChar() {
        return firstChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.first_char
     *
     * @param firstChar the value for car_brand.first_char
     *
     * @mbggenerated
     */
    public void setFirstChar(String firstChar) {
        this.firstChar = firstChar == null ? null : firstChar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.spell
     *
     * @return the value of car_brand.spell
     *
     * @mbggenerated
     */
    public String getSpell() {
        return spell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.spell
     *
     * @param spell the value for car_brand.spell
     *
     * @mbggenerated
     */
    public void setSpell(String spell) {
        this.spell = spell == null ? null : spell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.all_spell
     *
     * @return the value of car_brand.all_spell
     *
     * @mbggenerated
     */
    public String getAllSpell() {
        return allSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.all_spell
     *
     * @param allSpell the value for car_brand.all_spell
     *
     * @mbggenerated
     */
    public void setAllSpell(String allSpell) {
        this.allSpell = allSpell == null ? null : allSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.name_spell
     *
     * @return the value of car_brand.name_spell
     *
     * @mbggenerated
     */
    public String getNameSpell() {
        return nameSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.name_spell
     *
     * @param nameSpell the value for car_brand.name_spell
     *
     * @mbggenerated
     */
    public void setNameSpell(String nameSpell) {
        this.nameSpell = nameSpell == null ? null : nameSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.name_all_spell
     *
     * @return the value of car_brand.name_all_spell
     *
     * @mbggenerated
     */
    public String getNameAllSpell() {
        return nameAllSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.name_all_spell
     *
     * @param nameAllSpell the value for car_brand.name_all_spell
     *
     * @mbggenerated
     */
    public void setNameAllSpell(String nameAllSpell) {
        this.nameAllSpell = nameAllSpell == null ? null : nameAllSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.introduction
     *
     * @return the value of car_brand.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.introduction
     *
     * @param introduction the value for car_brand.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.sale_status
     *
     * @return the value of car_brand.sale_status
     *
     * @mbggenerated
     */
    public Byte getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.sale_status
     *
     * @param saleStatus the value for car_brand.sale_status
     *
     * @mbggenerated
     */
    public void setSaleStatus(Byte saleStatus) {
        this.saleStatus = saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.is_enabled
     *
     * @return the value of car_brand.is_enabled
     *
     * @mbggenerated
     */
    public Byte getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.is_enabled
     *
     * @param isEnabled the value for car_brand.is_enabled
     *
     * @mbggenerated
     */
    public void setIsEnabled(Byte isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.is_removed
     *
     * @return the value of car_brand.is_removed
     *
     * @mbggenerated
     */
    public Byte getIsRemoved() {
        return isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.is_removed
     *
     * @param isRemoved the value for car_brand.is_removed
     *
     * @mbggenerated
     */
    public void setIsRemoved(Byte isRemoved) {
        this.isRemoved = isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.create_time
     *
     * @return the value of car_brand.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.create_time
     *
     * @param createTime the value for car_brand.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.update_time
     *
     * @return the value of car_brand.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.update_time
     *
     * @param updateTime the value for car_brand.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.do_time
     *
     * @return the value of car_brand.do_time
     *
     * @mbggenerated
     */
    public Integer getDoTime() {
        return doTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.do_time
     *
     * @param doTime the value for car_brand.do_time
     *
     * @mbggenerated
     */
    public void setDoTime(Integer doTime) {
        this.doTime = doTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.sync_time
     *
     * @return the value of car_brand.sync_time
     *
     * @mbggenerated
     */
    public Integer getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.sync_time
     *
     * @param syncTime the value for car_brand.sync_time
     *
     * @mbggenerated
     */
    public void setSyncTime(Integer syncTime) {
        this.syncTime = syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", otherName=").append(otherName);
        sb.append(", englishName=").append(englishName);
        sb.append(", countryId=").append(countryId);
        sb.append(", logoUrl=").append(logoUrl);
        sb.append(", logoMeaning=").append(logoMeaning);
        sb.append(", firstChar=").append(firstChar);
        sb.append(", spell=").append(spell);
        sb.append(", allSpell=").append(allSpell);
        sb.append(", nameSpell=").append(nameSpell);
        sb.append(", nameAllSpell=").append(nameAllSpell);
        sb.append(", introduction=").append(introduction);
        sb.append(", saleStatus=").append(saleStatus);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append(", isRemoved=").append(isRemoved);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", doTime=").append(doTime);
        sb.append(", syncTime=").append(syncTime);
        sb.append("]");
        return sb.toString();
    }
}