package com.qf.with_my_car.pojo;

import lombok.Data;

import java.io.Serializable;
@Data
public class MemberCar implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.member_id
     *
     * @mbggenerated
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.make_id
     *
     * @mbggenerated
     */
    private Integer makeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.car_id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.buy_year
     *
     * @mbggenerated
     */
    private Integer buyYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.current_mileage
     *
     * @mbggenerated
     */
    private Integer currentMileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_car.last_update_time
     *
     * @mbggenerated
     */
    private Integer lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_car
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.id
     *
     * @return the value of member_car.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.id
     *
     * @param id the value for member_car.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.member_id
     *
     * @return the value of member_car.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.member_id
     *
     * @param memberId the value for member_car.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.brand_id
     *
     * @return the value of member_car.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.brand_id
     *
     * @param brandId the value for member_car.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.make_id
     *
     * @return the value of member_car.make_id
     *
     * @mbggenerated
     */
    public Integer getMakeId() {
        return makeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.make_id
     *
     * @param makeId the value for member_car.make_id
     *
     * @mbggenerated
     */
    public void setMakeId(Integer makeId) {
        this.makeId = makeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.model_id
     *
     * @return the value of member_car.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.model_id
     *
     * @param modelId the value for member_car.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.car_id
     *
     * @return the value of member_car.car_id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.car_id
     *
     * @param carId the value for member_car.car_id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.buy_year
     *
     * @return the value of member_car.buy_year
     *
     * @mbggenerated
     */
    public Integer getBuyYear() {
        return buyYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.buy_year
     *
     * @param buyYear the value for member_car.buy_year
     *
     * @mbggenerated
     */
    public void setBuyYear(Integer buyYear) {
        this.buyYear = buyYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.current_mileage
     *
     * @return the value of member_car.current_mileage
     *
     * @mbggenerated
     */
    public Integer getCurrentMileage() {
        return currentMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.current_mileage
     *
     * @param currentMileage the value for member_car.current_mileage
     *
     * @mbggenerated
     */
    public void setCurrentMileage(Integer currentMileage) {
        this.currentMileage = currentMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.remark
     *
     * @return the value of member_car.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.remark
     *
     * @param remark the value for member_car.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.type
     *
     * @return the value of member_car.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.type
     *
     * @param type the value for member_car.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.create_time
     *
     * @return the value of member_car.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.create_time
     *
     * @param createTime the value for member_car.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_car.last_update_time
     *
     * @return the value of member_car.last_update_time
     *
     * @mbggenerated
     */
    public Integer getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_car.last_update_time
     *
     * @param lastUpdateTime the value for member_car.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Integer lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", brandId=").append(brandId);
        sb.append(", makeId=").append(makeId);
        sb.append(", modelId=").append(modelId);
        sb.append(", carId=").append(carId);
        sb.append(", buyYear=").append(buyYear);
        sb.append(", currentMileage=").append(currentMileage);
        sb.append(", remark=").append(remark);
        sb.append(", type=").append(type);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}