package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.CarBrand;
import com.qf.with_my_car.pojo.CarBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CarBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int countByExample(CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int deleteByExample(CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int insert(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int insertSelective(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    List<CarBrand> selectByExampleWithRowbounds(CarBrandExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    List<CarBrand> selectByExample(CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    CarBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CarBrand record, @Param("example") CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CarBrand record, @Param("example") CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarBrand record);
}