package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.MemberPoint;
import com.qf.with_my_car.pojo.MemberPointExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface MemberPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int countByExample(MemberPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int deleteByExample(MemberPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int insert(MemberPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int insertSelective(MemberPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    List<MemberPoint> selectByExampleWithRowbounds(MemberPointExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    List<MemberPoint> selectByExample(MemberPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    MemberPoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberPoint record, @Param("example") MemberPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberPoint record, @Param("example") MemberPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberPoint record);
}