package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.MemberFav;
import com.qf.with_my_car.pojo.MemberFavExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MemberFavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int countByExample(MemberFavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int deleteByExample(MemberFavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int insert(MemberFav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int insertSelective(MemberFav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    List<MemberFav> selectByExampleWithRowbounds(MemberFavExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    List<MemberFav> selectByExample(MemberFavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    MemberFav selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberFav record, @Param("example") MemberFavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberFav record, @Param("example") MemberFavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberFav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberFav record);
}