package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.MemberProfile;
import com.qf.with_my_car.pojo.MemberProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MemberProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int countByExample(MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int deleteByExample(MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int insert(MemberProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int insertSelective(MemberProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    List<MemberProfile> selectByExampleWithRowbounds(MemberProfileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    List<MemberProfile> selectByExample(MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    MemberProfile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberProfile record, @Param("example") MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberProfile record, @Param("example") MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberProfile record);
}