package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.MemberCar;
import com.qf.with_my_car.pojo.MemberCarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MemberCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int countByExample(MemberCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int deleteByExample(MemberCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int insert(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int insertSelective(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    List<MemberCar> selectByExampleWithRowbounds(MemberCarExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    List<MemberCar> selectByExample(MemberCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    MemberCar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberCar record, @Param("example") MemberCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberCar record, @Param("example") MemberCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberCar record);
}